

spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/spring?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    password: 666
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss


logging:
  level:
    com:
      shangma:
        cn: debug
  file:
    path: E://


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9999

alibabaupload:
  accessKeyId: LTAI5tGywQz2oaUxkAVqpLq1
  accessKeySecret: M3boU24MoiOTAY7NoUqob6vqnShYmq
  endpoint: https://oss-cn-beijing.aliyuncs.com
  url: https://wwwshuai.oss-cn-beijing.aliyuncs.com/



